apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-example.fullname" . }}-api
  labels:
    {{- include "k8s-example.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ include "k8s-example.fullname" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "k8s-example.fullname" . }}-api
        {{- include "k8s-example.labels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.api.port }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.api.port }}
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.api.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{- toYaml .Values.api.resources | nindent 12 }}
