{{- if .Values.controller.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-example.fullname" . }}-controller
  labels:
    {{- include "k8s-example.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-example.fullname" . }}-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "k8s-example.fullname" . }}-controller
{{- end }}
