{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-example.fullname" . }}-controller
  labels:
    {{- include "k8s-example.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
{{- end }}
